language: python

python:
  - "3.5"

script:
  - python febay/manage.py test

install:
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - docker run --name mysql -d mysql:5.7.14
  - docker-compose up
  - export DJANGO_SETTINGS_MODULE="febay.settings"
  - export PYTHONPATH="$HOME/builds/kevinavalo/app"


services:
  - docker

sudo: false


before_script:
  - docker exec -it mysql 'CREATE DATABASE cs4501;'
  - docker exec -it mysql "grant all on cs4501.* to 'www'@'localhost';"
