language: python

python:
  - "3.5"

script:
  - python febay/manage.py test

services:
  - docker
  - mysql

sudo: required

before_install:

  - export DJANGO_SETTINGS_MODULE="febay.settings"
  - export PYTHONPATH="$HOME/builds/kevinavalo/app"
  - mysql -e 'CREATE DATABASE cs4501;'
  - mysql -e 'grant all on cs4501.* to 'www'@'localhost';'
