models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./InternetScaleAppsProject/febay:/app
    ports:
      - "8001:8000"
    command: bash -c "python /app/manage.py makemigrations" && "python /app/manage.py migrate" && "python /app/manage.py loaddata /app/db.json" && "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/febay/wsgi.py"